### ISSUE TITLE
"caffe::LayerParameter" has no member "ng_param"

### ISSUE THREAD

**Issue by kecaiwu** [HolmesShuan/SNNs-Self-Normalizing-Neural-Networks-Caffe-Reimplementation#1]
when i compile the caffe with the selu layer, I get the "caffe::LayerParameter" has no member "ng_param" error in the selu_layer.cu, can you give some advice, thx.

**Comment by HolmesShuan** [comment]
Sorry, my mistake. New commit has been made.
