### ISSUE TITLE
NetUpgradeTest.TestUpgradeV1LayerType test Failed

### ISSUE THREAD

**Issue by bitcurian** [HolmesShuan/SNNs-Self-Normalizing-Neural-Networks-Caffe-Reimplementation#4]
I get the following error, after copying the files and making the requisite changes in caffe.proto, when I run the tests. I believe it to be a bug with the current caffe version and the addition of the SELU layers.

I'd be grateful if a fix could be suggested for it.

Specs:
Caffe Version 1.0.0
Nvidia GTX 970m
Cudnn 6.0
CUDA 8
Linux mint 18

![image](https://user-images.githubusercontent.com/26731323/27766006-ff432a2a-5e8f-11e7-99fc-1ab75a6906ac.png)

**Comment by HolmesShuan** [comment]
Sorry about that. It was our mistake creating this repository without fully `make runtest`. I have checked the recent updated caffe.proto(in readme.md), it could pass the `make all` on our devices(Our Caffe Version ~2016.12, 1.0.0 may encounter some compatibility problems, not so sure). Actually, we didn't write test file for this layer, in some sense, `runtest` can be skipped. This bug concerns an older deprecated specification format, won't affect your usage of SNNs.
