### ISSUE TITLE
How to initialize weights in caffe for SNN

### ISSUE THREAD

**Issue by jczaja** [HolmesShuan/SNNs-Self-Normalizing-Neural-Networks-Caffe-Reimplementation#5]
Hi,

According to my (far from complete) understanding SNNs require initalization of weights
so it is gaussian distribution with stddev 1/sqrt(n). So It is very similar to MSRAFiller just stddev is 1/sqrt(n) not 2/sqrt(n). Code in this repo does not have initialization of SNN added, so there is probably easy way to have this SNN initialization done? If not then it could be good to create (based on MSRA) SNN initialization?

**Comment by HolmesShuan** [comment]
[Official GitHub Link](https://github.com/bioinf-jku/SNNs). U may turn to the author of SNNs for more details. How to create default value is still under discussion, as we know.
